### ISSUE TITLE
1/23每日一题

### ISSUE THREAD

**Issue by bertilchan** [FangzhouSu/FE-Harvester-studyEveryday#11]
1.let、const、var区别
2.数组去重的方法有哪些？
3.vue双向绑定的原理
4.力扣经典题：70. 爬楼梯

**Comment by FangzhouSu** [comment]
数组去重 遍历，哈希表（map或简单Set），排序后冒泡去重~

**Comment by FangzhouSu** [comment]
- let const 块级作用域+暂时死区导致变量提升失效 与var的全局作用域+变量提升；
- let var定义的变量可变 const不可变 
> #### const的本质（来自阮大ES6教程）

`const`实际上保证的，并不是变量的值不得改动，而是**变量指向的那个内存地址所保存的数据不得改动**。

- 对于简单类型的数据（数值、字符串、布尔值），值就保存在变量指向的那个内存地址，因此等同于常量。
- 但对于复合类型的数据（主要是对象和数组），变量指向的内存地址，保存的只是一个指向实际数据的指针，`const`只能保证这个指针是固定的（即总是指向另一个固定的地址），至于它指向的数据结构是不是可变的，就完全不能控制了。因此，将一个对象声明为常量必须非常小心。

**Comment by bertilchan** [comment]
1.let、const、var区别
（1）var和let是用来声明一个变量，而const是用来声明一个常量
（2）变量提升：var声明的变量存在变量提升，即变量可以在声明之前使用，值为undefined；let和const不存在变量提升，即它们所声明的变量一定要在声明后使用，否则会报错
（3）暂时性死区：var不存在暂时性死区；let和const存在暂时性死区，只有等到声明变量的那一行代码出现，才可以获取和使用该变量
（4）块级作用域：var不存在块级作用域；let和const存在块级作用域
（5）重复声明：var允许重复声明变量；let和const在同一作用域下不允许重复声明变量
（6）修改值：var和let可以修改声明的变量；const声明一个只读的常量，声明后常量的值就不能改变。
（7）使用：能用const的情况尽量使用const，其他情况下大多数使用let，避免使用var

2.数组去重的方法有哪些？
* 传统方式：遍历元素挨个比较、去重
```javascript
function unique(arr) {
    const res = []
    arr.forEach(item => {
        if (res.indexOf(item) < 0) {
            res.push(item)
        }
    })
    return res
}
```
* 使用Set（计算效率高） 
```javascript
function unique(arr) {
    const set = new Set(arr)
    return [...set]
}
```
3.vue双向绑定的原理
整体思路是数据劫持+观察者模式
对象内部通过 defineReactive 方法，使用 Object.defineProperty 将属性进行劫持（只会劫持已经存在的属性），数组则是通过重写数组方法来实现。当页面使用对应属性时，每个属性都拥有自己的 dep 属性，存放他所依赖的 watcher（依赖收集），当属性变化后会通知自己对应的 watcher 去更新(派发更新)。

参考：https://juejin.cn/post/6935344605424517128

4.力扣经典题：70. 爬楼梯
* 方法一 —— 记忆化递归
由于递归太耗时，可以用记忆化递归避免重复的计算。
**解题过程：**
1.先对n为0这种特殊情况进行处理，然后n为1和2时直接return即可
2.memo数组：存储中间结果，避免重复计算
3.接下来就是判断memo[n]是否存在，如果计算过即存在，直接返回，无需重复计算；若不存在，则进行递归计算，为前两个之和。
**代码**
```javascript
/**
 * @param {number} n
 * @return {number}
 */
const memo = []
var climbStairs = function(n) {
    if( n === 0) return 1
    if(n <= 3) return n
    if(memo[n]) {
        return memo[n]
    }else {
        memo[n] = climbStairs(n-1) + climbStairs(n-2)
    }
    return memo[n]
}
```
* 方法二 —— 动态规划（常规）
**解题过程：**
1.如果只有0阶或者1阶，则直接返回n。(后面直接从2阶及以上开始，防止0/1阶导致数组出现空指针)
2.dp[i]：爬到i层楼梯，有dp[i]种方法
3.从i=3开始遍历，因为必须要有前两个存在，且存在dp[n] = dp[n-1] + dp[n-2]的关系。
**代码**
```javascript
/**
 * @param {number} n
 * @return {number}
 */
var climbStairs = function(n) {
    if (n <= 1) return n

    const dp = new Array(n)
    dp[1] = 1
    dp[2] = 2
    for (let i = 3; i <= n; i++) {
        dp[i] = dp[i-1] + dp[i-2]
    }
    return dp[n]
}
```
* 方法三 —— 动态规划（滚动数组思想 ==> 优化空间为O(1)）
**解题过程：**
1.先定义好三个常量，利用向左移动的思想，使得计算过程中只使用了常数个变量，且存在r = p + q的关系
2.只用常数个变量作为辅助空间,故渐进空间复杂度为 O(1)
**代码**
```javascript
/**
 * @param {number} n
 * @return {number}
 */
var climbStairs = function(n) {
    let p = 0, q = 0, r = 1  
    for (let i = 1; i<= n; i++) {
        p = q
        q = r
        r = p + q
    }
    return r
};
```
* 方法四 —— 动态规划（非数组法）
目前所有的动态规划都有这两种写法：用数组或非数组。不用数组的也可以理解成滑动窗口、双指针。
**解题过程：**
1.当有0、1、2个台阶时，分别有0、1、2种方法，用return直接返回
2.prev用于记录前一个台阶，初始值为第一个台阶,curr用于记录当前台阶，初始值为第二个台阶
3.然后从第三个台阶开始循环，执行到第n个台阶。
**代码**
```javascript
var climbStairs = function(n) {
    if(n <= 2) {
        return n
    }
    let prev = 1
    let curr = 2
    for(let i = 3;i <= n; i++) {
        let temp = prev + curr
        prev = curr
        curr = temp
    }
    return curr
}
```

**Comment by bertilchan** [comment]
> * let const 块级作用域+暂时死区导致变量提升失效 与var的全局作用域+变量提升；
> * let var定义的变量可变 const不可变
> 
> > #### const的本质（来自阮大ES6教程）
> 
> `const`实际上保证的，并不是变量的值不得改动，而是**变量指向的那个内存地址所保存的数据不得改动**。
> 
> * 对于简单类型的数据（数值、字符串、布尔值），值就保存在变量指向的那个内存地址，因此等同于常量。
> * 但对于复合类型的数据（主要是对象和数组），变量指向的内存地址，保存的只是一个指向实际数据的指针，`const`只能保证这个指针是固定的（即总是指向另一个固定的地址），至于它指向的数据结构是不是可变的，就完全不能控制了。因此，将一个对象声明为常量必须非常小心。
