### ISSUE TITLE
1/30每日一题

### ISSUE THREAD

**Issue by bertilchan** [FangzhouSu/FE-Harvester-studyEveryday#16]
1.水平垂直居中的方法
2.ES6有哪些新特性?
3.宏任务和微任务都有哪些？有什么区别？
4.力扣：1.两数之和

**Comment by bertilchan** [comment]
1.水平垂直居中* 第一种：inline元素

```
text-aligin: center
line-height的值等于height值
```

* 第二种：利用绝对定位，先将元素的左上角通过 top:50%和 left:50%定位到页面的中心，然后再通过 margin 负值来调整元素的中心点到页面的中心。该方法适用于盒子宽高已知的情况

```
.parent {
    position: relative;
}

.child {
    position: absolute;
    top: 50%;
    left: 50%;
    margin-top: -50px;     /* 自身 height 的一半 */
    margin-left: -50px;    /* 自身 width 的一半 */
}
```

* 第三种：利用绝对定位，先将元素的左上角通过 top:50%和 left:50%定位到页面的中心，然后再通过 translate 来调整元素的中心点到页面的中心。该方法需要**考虑浏览器兼容问题。**

```
.parent {
    position: relative;
}

.child {
    position: absolute;
    left: 50%;
    top: 50%;
    transform: translate(-50%,-50%);
}
```

* 第四种：利用绝对定位，设置四个方向的值都为 0，并将 margin 设置为 auto，由于宽高固定，因此对应方向实现平分，可以实现水平和垂直方向上的居中。该方法适用于盒子有宽高的情况：

```
.parent {
    position: relative;
}

.child {
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    margin: auto;
}
```

- 第五种：使用 flex 布局，通过 align-items:center 和 justify-content:center 设置容器的垂直和水平方向上为居中对齐，然后它的子元素也可以实现垂直和水平的居中。该方法要**考虑兼容的问题**，该方法在移动端用的较多：

```
.parent {
    display: flex;
    justify-content:center;
    align-items:center;
}
```

* 第六种：如果父元素设置了flex布局，只需要给子元素加上`margin:auto;`就可以实现垂直居中布局

```
.parent{
    display:flex;
}
.child{
    margin: auto;
}
```

2.ES6新特性
1）let声明变量和const声明常量，两个都有块级作用域
　　ES5中是没有块级作用域的，并且var有变量提升，在let中，使用的变量一定要进行声明

2）箭头函数
ES6中的函数定义不再使用关键字function()，而是利用了()=>来进行定义

3）模板字符串
模板字符串是增强版的字符串，用反引号（`）标识，可以当作普通字符串使用，也可以用来定义多行字符串

4）解构赋值
ES6 允许按照一定模式，从数组和对象中提取值，对变量进行赋值

5）for of循环
for...of循环可以遍历数组、Set和Map结构、某些类似数组的对象、对象，以及字符串

6）import、export导入导出
ES6标准中，Js原生支持模块(module)。将JS代码分割成不同功能的小块进行模块化，将不同功能的代码分别写在不同文件中，各模块只需导出公共接口部分，然后通过模块的导入的方式可以在其他地方使用

7）set数据结构
Set数据结构，类似数组。所有的数据都是唯一的，没有重复的值。它本身是一个构造函数

8）... 展开运算符
可以将数组或对象里面的值展开；还可以将多个值收集为一个变量

9）修饰器 @
decorator是一个函数，用来修改类甚至于是方法的行为。修饰器本质就是编译时执行的函数

10）class 类的继承
ES6中不再像ES5一样使用原型链实现继承，而是引入Class这个概念

11）async、await
使用 async/await, 搭配promise,可以通过编写形似同步的代码来处理异步流程, 提高代码的简洁性和可读性
async 用于申明一个 function 是异步的，而 await 用于等待一个异步方法执行完成

12）promise
Promise是异步编程的一种解决方案，比传统的解决方案（回调函数和事件）更合理、强大

13）Symbol
Symbol是一种基本类型。Symbol 通过调用symbol函数产生，它接收一个可选的名字参数，该函数返回的symbol是唯一的

14）Proxy代理
使用代理（Proxy）监听对象的操作，然后可以做一些相应事情

3.宏任务和微任务
* 宏任务：setTimeout、setInterval、ajax、DOM事件
* 微任务：promise、async/await

区别：
* 微任务执行时机比宏任务要早，微任务在DOM 渲染前触发，宏任务在DOM 渲染后触发

4.力扣：1.两数之和
一种比较高效的做法：巧用js中的map（原题可以看这里，之前总结的：https://blog.csdn.net/Bertil/article/details/120425114 
**解题过程：**
1.用map来存放{数组元素值，坐标}这样的键值对
2.运用逆向解法，即用target减去数组中的某个元素，然后来判断map中是否有相同的值，若有则存在满足条件的答案，返回两个坐标即可；若没有，则保存{数组中某个元素值，对应的坐标}到map对象中。依次遍历即可判断是否有满足条件的两个元素。

## 代码

```javascript
var twoSum = function(nums, target) {
    map = new Map()
    for(let i = 0; i < nums.length; i++) {
        x = target - nums[i]
        if(map.has(x)) {
            return [map.get(x),i]
        }
        map.set(nums[i],i)
    }
};
```

**Comment by FangzhouSu** [comment]
水平垂直居中 之前写过一个小文章 —— https://juejin.cn/post/7009662518406676488 
ES6新特性部分感谢总结~ 根据[阮老师的书](https://es6.ruanyifeng.com/#docs/intro) 再做一些补充——
![image](https://user-images.githubusercontent.com/75036021/151694010-1ad1d36c-4b53-4249-8169-5c693c064a31.png)

另外 宏任务微任务 事件循环模型的内容分享一篇不错的文章 [10分钟理解JS引擎的执行机制](https://segmentfault.com/a/1190000012806637)
两数之和用哈希表应该最优解了吧 老铁没毛病
