### ISSUE TITLE
22/1/13每日一题

### ISSUE THREAD

**Issue by 1148716206** [FangzhouSu/FE-Harvester-studyEveryday#2]
1.箭头函数与普通函数的区别?

2.this指向哪⾥？

3.扩展运算符的作用及使用场景?

> 仓管来加道经典题 大家来瞅一眼呗hh 昨天做了树 今天做个超级经典数组题吧！ 

4. [217. 存在重复元素](https://leetcode-cn.com/problems/contains-duplicate/)

**Comment by UnicornHang** [comment]
第一题：
1.箭头函数的参数只有一个时，可以省略小括号，函数里面的执行语句只有一条时，可以省略花括号
2.箭头函数本身没有this，它会继承作用域链上一层的this
3.箭头函数没有argument
4.箭头函数不能使用call, bind, apply来改变this指向
5.箭头函数不能作为构造函数使用

**Comment by LianTianNo1** [comment]
## 2022.01.13

### 1.箭头函数与普通函数的区别



> 自己总结

#### 1：写法不一样

```js
function foo() {
    console.log('1')
}
let foo = ()=> {
    console.log('1')
}
```

#### 2：普通函数存在变量提升的现象

```js
//普通函数
foo()
function foo() {
    console.log('1')
}

//箭头函数
foo() //报错 foo is not a function
let foo = ()=> {
    console.log('1')
}

```

#### 3：箭头函数不能作为构造函数使用

```js
let Person = (name) => {
    this.name = name
}
let xiao_ming = new Person('小明')
console.log(xiao_ming.name) //undefined
```

#### 4：两者this的指向不同

普通函数的this指向的是谁调用该函数就指向谁

箭头函数的this指向的是在你书写代码时候的上下文环境对象的this，如果没有上下文环境对象，那么就指向最外层对象window。

#### 5：箭头函数的arguments指向它的父级函数所在作用域的arguments

```js
function foo() {
  console.log(arguments)
  let foo1 = () => {
    console.log(arguments)
  }
  foo1()
}
foo('test')

//[Arguments] { '0': 'test' }
//[Arguments] { '0': 'test' }
```

#### 6：箭头函数没有new.target

先说明下new.target是干嘛的，这家伙是用来检测函数是否被当做构造函数使用，他会返回一个指向构造函数的引用。

因为箭头函数不能当做构造函数使用，自然是没有new.target的。



### 2.this指向哪⾥？



> 自己总结

- 普通函数中：this->window
- 定时器中：this->window
- 构造函数中：this->当前实例化的对象
- 事件处理函数中：this->事件触发对象
- 在 js 中一般理解就是谁调用这个 this 就指向谁





### 3.扩展运算符的作用及使用场景




> 自己总结

#### 将一个数组转为用逗号分隔的参数序列。

```js
console.log(...[1, 2, 3]) // 1 2 3

console.log(1, ...[2, 3, 4], 5) //1 2 3 4 5
```

#### 普通函数中使用

```js
function push(array, ...items) {
  array.push(...items);
}

function add(x, y) {
  return x + y;
}

var numbers = [1, 2];
add(...numbers) // 3
```

#### 替代 apply 方法调用函数

```js
// ES5 的写法
Math.max.apply(null, [14, 3, 77])

// ES6 的写法
Math.max(...[14, 3, 77])

// 等同于
Math.max(14, 3, 77);
```

#### 合并数组

```js
var arr1 = ['a', 'b'];
var arr2 = ['c'];
var arr3 = ['d', 'e'];

// ES5的合并数组
arr1.concat(arr2, arr3)  // [ 'a', 'b', 'c', 'd', 'e' ]

// ES6的合并数组
[...arr1, ...arr2, ...arr3]  // [ 'a', 'b', 'c', 'd', 'e' ]
```

#### 与解构赋值结合

```js
const [first, ...rest] = [1, 2, 3, 4, 5];
first // 1
rest  // [2, 3, 4, 5]

const [first, ...rest] = [];
first // undefined
rest  // []

const [first, ...rest] = ["foo"];
first  // "foo"
rest   // []
```

如果将扩展运算符用于数组赋值，只能放在参数的最后一位，否则会报错。

```js
const [...butLast, last] = [1, 2, 3, 4, 5];  // 报错

const [first, ...middle, last] = [1, 2, 3, 4, 5];  // 报错
```

#### 将字符串转为数组

```js
var str = 'hello';

// ES5  
var arr1 = str.split('');  // [ "h", "e", "l", "l", "o" ] 

// ES6  
var arr2 = [...str];  // [ "h", "e", "l", "l", "o" ] 
```

#### 实现了 Iterator 接口的对象

任何Iterator接口的对象，都可以用扩展运算符转为真正的数组。

```js
var domList = document.querySelectorAll('span');
var array = [...domList];
```

**Comment by FangzhouSu** [comment]
【1】来分享下箭头函数的代码规范吧！这两天正好在看
https://github.com/lin-123/javascript#%E7%AE%AD%E5%A4%B4%E5%87%BD%E6%95%B0 
- [8.1](https://github.com/lin-123/javascript#arrows--use-them) 当你一定要用函数表达式（在回调函数里）的时候，使用箭头函数。 eslint: [`prefer-arrow-callback`](http://eslint.org/docs/rules/prefer-arrow-callback.html), [`arrow-spacing`](http://eslint.org/docs/rules/arrow-spacing.html)

  > 为什么？箭头函数中的 `this` 与定义该函数的上下文中的 `this` 一致，这通常才是你想要的。而且箭头函数是更简洁的语法。

  > 什么时候不用箭头函数：如果你的函数逻辑较复杂，你应该把它单独写入一个命名函数里头。

  ```js
  // bad
  [1, 2, 3].map(function (x) {
    const y = x + 1;
    return x * y;
  });
  
  // good
  [1, 2, 3].map((x) => {
    const y = x + 1;
    return x * y;
  });
  ```



- [8.2](https://github.com/lin-123/javascript#arrows--implicit-return) 如果函数体由一个没有副作用的 [表达式](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_Operators#Expressions) 语句组成，删除大括号和 return。否则，使用大括号和 `return` 语句。 eslint: [`arrow-parens`](https://eslint.org/docs/rules/arrow-parens.html), [`arrow-body-style`](https://eslint.org/docs/rules/arrow-body-style.html)

  > 为什么？语法糖，当多个函数链在一起的时候好读。
简单来说就是：
如果回调函数有return 则可以省略大括号和return ——可读性增强~
如果回调函数没有return 则最好加上大括号 ——减少副作用

  ```js
  // bad
  [1, 2, 3].map((number) => {
    const nextNumber = number + 1;
    `A string containing the ${nextNumber}.`;
  });
  
  // good
  [1, 2, 3].map((number) => `A string containing the ${number + 1}.`);
  
  // good
  [1, 2, 3].map((number) => {
    const nextNumber = number + 1;
    return `A string containing the ${nextNumber}.`;
  });
  
  // good
  [1, 2, 3].map((number, index) => ({
    [index]: number,
  }));
  
  // 没有明显的 return 语句，可能存在副作用。
  function foo(callback) {
    const val = callback();
    if (val === true) {
      // 当 callback 返回 true 时...
    }
  }
  
  let bool = false;
  
  // bad
  foo(() => bool = true);
  
  
  // good
  foo(() => {
    bool = true;
  });
  ```



- [8.6](https://github.com/lin-123/javascript#whitespace--implicit-arrow-linebreak) 使箭头函数体有一个清晰的返回。 eslint: [`implicit-arrow-linebreak`](https://eslint.org/docs/rules/implicit-arrow-linebreak)

  ```js
  // bad
  (foo) =>
    bar;
  
  (foo) =>
    (bar);
  
  // good
  (foo) => bar;
  (foo) => (bar);
  (foo) => (
     bar
  )
  ```

- [8.3](https://github.com/lin-123/javascript#arrows--paren-wrap) 如果表达式涉及多行，把他包裹在圆括号里以**提高可读性**。

  > 这里确实经常被我忽略！加上了括号确实好读很多！

  > 为什么？这样能清晰地**显示函数的开始位置和结束位置**。

  ```js
  // bad
  ['get', 'post', 'put'].map(httpMethod => Object.prototype.hasOwnProperty.call(
      httpMagicObjectWithAVeryLongName,
      httpMethod
    )
  );
  
  // good
  ['get', 'post', 'put'].map(httpMethod => (
    Object.prototype.hasOwnProperty.call(
      httpMagicObjectWithAVeryLongName,
      httpMethod
    )
  ));
  ```

- [8.4](https://github.com/lin-123/javascript#arrows--one-arg-parens) 在箭头函数参数两头，总是使用小括号包裹住参数，这样做使代码更清晰且一致. eslint: [`arrow-parens`](https://eslint.org/docs/rules/arrow-parens.html)

  > 我写箭头函数是有多不规范，，，下次参数只有一个的时候也不要忘记加括号啊！

  > 为什么？当你想要添加或删除参数时能比较省事。

  ```js
  // bad
  [1, 2, 3].map(x => x * x);
  
  // good
  [1, 2, 3].map((x) => x * x);
  
  // bad
  [1, 2, 3].map(number => (
    `A long string with the ${number}. It’s so long that we don’t want it to take up space on the .map line!`
  ));
  
  // good
  [1, 2, 3].map((number) => (
    `A long string with the ${number}. It’s so long that we don’t want it to take up space on the .map line!`
  ));
  ```

- [8.5](https://github.com/lin-123/javascript#arrows--confusing) 避免箭头函数（`=>`）和比较操作符（`<=`, `>=`）混淆. eslint: [`no-confusing-arrow`](http://eslint.org/docs/rules/no-confusing-arrow)

  > 这里之前也没主要到（也没碰到过）
  >
  > 之后在箭头函数中使用大于等于号和小于等于号时要加上**括号/大括号**来避免混淆

  ```js
  // bad
  const itemHeight = (item) => item.height <= 256 ? item.largeSize : item.smallSize;
  
  // bad
  const itemHeight = (item) => item.height >= 256 ? item.largeSize : item.smallSize;
  
  // good
  const itemHeight = (item) => (item.height <= 256 ? item.largeSize : item.smallSize);
  
  // good
  const itemHeight = (item) => {
    const { height, largeSize, smallSize } = item;
    return height <= 256 ? largeSize : smallSize;
  };
  ```

**Comment by FangzhouSu** [comment]
【3】扩展运算符我能想到的一些点有——（欢迎补充）
- 将对象转换为数组 `let arr = [...obj]`
- 浅拷贝数组/对象 `let newArr = [...arr]` `const original = { a: 1, b: 2 }; const copy = { ...original, c: 3 };`
- 获取一个对象的某几个属性 `const { a, ...noAItems } = copy;// noAItems=> { b: 2, c: 3 }`
- 将可迭代对象转换为数组 —— 尽量不要用Array.from() 
![image](https://user-images.githubusercontent.com/75036021/149280061-8adc9fb6-c4ec-4324-b0f2-d8f63e25f396.png)
- 收集数组
![image](https://user-images.githubusercontent.com/75036021/149280372-1acb9b98-52c6-4cfe-b61d-7f5e8fe415af.png)

**Comment by FangzhouSu** [comment]
【4】[217. 存在重复元素](https://leetcode-cn.com/problems/contains-duplicate/)
经典的数组查重问题！

- 【1】利用判重API `indexOf`构建去重辅助数组

```js
var containsDuplicate = function(nums) {
    let newArr = []
    for(let i = 0; i < nums.length; i++) {
        if(newArr.indexOf(nums[i]) === -1) {
            newArr.push(nums[i])
        }
    }
    return newArr.length !== nums.length
};
```

执行用时较高！想必是`indexOf`方法的锅咯~

- 【2】利用数据结构Set 构造只有单一元素的Set对象,判断Set对象与原数组长度是否相同

```js
var containsDuplicate = function(nums) {
    let newArr = new Set(nums)
    return newArr.size !== nums.length
};
```

- 同理 使用哈希表记录出现的次数也可以~

这里用Set其实更好哈~主要上面刚用过 换个口儿😄

```js
var containsDuplicate = function(nums) {
    let map = new Map()
    for(let i = 0; i < nums.length; i++) {
        if(map.has(nums[i])) {
            return true
        }
        else{
            map.set(nums[i], 1)
        }
    }
    return false
};
```

时间复杂度O(N)

空间复杂度O(N)

- 【3】排序后冒泡比较

这里可以拓展炫技手写个排序出来？😏

```js
var containsDuplicate = function(nums) {
    nums.sort((a, b) => a - b)
    for(let i = 0; i < nums.length - 1; i++) {
        if(nums[i] === nums[i + 1]) {
            return true
        }
    }
    return false
};
```

时间复杂度O(N*log~N~)

空间复杂度O(log~N~) 在这里应当考虑排序时递归调用栈的深度。

>  V8 引擎 sort 函数只给出了两种排序 InsertionSort 和 QuickSort，
>
>  - 数量小于10的数组使用 `InsertionSort`-插入排序
>  - 比10大的数组则使用 `QuickSort`-快速排序
>
>  详情见[V8 引擎array源码](https://github.com/v8/v8/blob/ad82a40509c5b5b4680d4299c8f08d6c6d31af3c/src/js/array.js) 710行开始 快排在760行处



- 【4】说干就干！来手写个快排！参考之前写过的一篇[Java题解](https://blog.csdn.net/qq_45704942/article/details/116448702?spm=1001.2014.3001.5502)（写得贼详细 每一步都拆分开来说了！），这篇文章是参考的leetcode主站的一篇[优秀图解 by 袁厨](https://leetcode-cn.com/problems/sort-an-array/solution/dong-hua-mo-ni-yi-ge-kuai-su-pai-xu-wo-x-7n7g/)~（好家伙连环参考）

快排分以下几步

1.选出基准值

2.使用[填坑法](https://leetcode-cn.com/problems/sort-an-array/solution/dong-hua-mo-ni-yi-ge-kuai-su-pai-xu-wo-x-7n7g/)，写一个partition函数将数组分为小于基准值和大于基准值两部分

3.递归完成快排！

下面代码里这个注释很清楚了吧！

另外还写了个[题解](https://leetcode-cn.com/problems/sort-an-array/solution/javascriptjava-chao-xiang-xi-ti-jie-tian-dsvc/) 搭配图看着更舒服哈~

```js
var sortArray = function(nums) {
    quicksort(nums, 0, nums.length - 1)// 调用快排方法
    return nums
};
var quicksort = function(nums, low, high) {
    if(low < high) {
        let index = partition(nums, low, high)// 得到用来将数组分成两部分（左面全小于index 右面全大于index）的索引
        quicksort(nums, low, index - 1)// 以第一轮得出的index为基准划分出左半区和右半区 对数组的左半区进行递归 将其全部变为有序
        quicksort(nums, index + 1, high)// 同理左半区
    }
}
var partition = function(arr, low, high) {
    let pivot = arr[low]// 选定第一个元素为基准值 把它拿出来 即为“挖坑”
    while(low < high) {
        // 【1】 挖了坑就需要填坑~从high指针开始向左找 
        while(low < high && arr[high] >= pivot) {
            high--
        }
        arr[low] = arr[high]// 一旦找到比坑对应值pivot小的 就扔到low那侧的坑里
        // 【2】 同【1】从low指针开始向右找填坑值
        while(low < high && arr[low] < pivot) {
            low++
        }
        arr[high] = arr[low]// 一旦找到比坑对应值pivot大的 就扔到high那侧的坑里
        //（刚刚这侧有一个值去填low那侧的坑了 所以出现了一个坑位~）
    }
    // 经过上面【1】【2】的不断迭代 low===high 此时这个位置即为基准位置
    arr[low] = pivot
    return low// 分区成功！返回定海神针~（此时low=high哦~）
}
```

> 再拓展补充下~
>
> - 不稳定的四种排序方法 **快选希堆** 
>
> - 最快的排序方法是**归并排序** 还有一个不常见的堆排序！ 时间复杂度为 n×log~n~
>
>   - 快速排序的平均时间复杂度是n×log~n~
>
>   ![img](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/7f79a76fa5224409bdcea8ed5cef1470~tplv-k3u1fbpfcp-zoom-1.awebp?)
>
> - 归并排序和快速排序的区别：
>
>   ![img](https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/431ac187d7ac4331abc3702407c3ab16~tplv-k3u1fbpfcp-zoom-1.awebp?)
>
>   - 归并是先拆开 从底下往上面排 
>   - 快排是每次都打乱一下 从上往下排

**Comment by FangzhouSu** [comment]
> 【4】[217. 存在重复元素](https://leetcode-cn.com/problems/contains-duplicate/) 经典的数组查重问题！
> 
> * 【1】利用判重API `indexOf`构建去重辅助数组
> 
> ```js
> var containsDuplicate = function(nums) {
>     let newArr = []
>     for(let i = 0; i < nums.length; i++) {
>         if(newArr.indexOf(nums[i]) === -1) {
>             newArr.push(nums[i])
>         }
>     }
>     return newArr.length !== nums.length
> };
> ```
> 
> 执行用时较高！想必是`indexOf`方法的锅咯~
> 
> * 【2】利用数据结构Set 构造只有单一元素的Set对象,判断Set对象与原数组长度是否相同
> 
> ```js
> var containsDuplicate = function(nums) {
>     let newArr = new Set(nums)
>     return newArr.size !== nums.length
> };
> ```
> 
> * 同理 使用哈希表记录出现的次数也可以~
> 
> 这里用Set其实更好哈~主要上面刚用过 换个口儿😄
> 
> ```js
> var containsDuplicate = function(nums) {
>     let map = new Map()
>     for(let i = 0; i < nums.length; i++) {
>         if(map.has(nums[i])) {
>             return true
>         }
>         else{
>             map.set(nums[i], 1)
>         }
>     }
>     return false
> };
> ```
> 
> 时间复杂度O(N)
> 
> 空间复杂度O(N)
> 
> * 【3】排序后冒泡比较
> 
> 这里可以拓展炫技手写个排序出来？😏
> 
> ```js
> var containsDuplicate = function(nums) {
>     nums.sort((a, b) => a - b)
>     for(let i = 0; i < nums.length - 1; i++) {
>         if(nums[i] === nums[i + 1]) {
>             return true
>         }
>     }
>     return false
> };
> ```
> 
> 时间复杂度O(N*log~N~)
> 
> 空间复杂度O(log~N~) 在这里应当考虑排序时递归调用栈的深度。
> 
> > V8 引擎 sort 函数只给出了两种排序 InsertionSort 和 QuickSort，
> > 
> > * 数量小于10的数组使用 `InsertionSort`-插入排序
> > * 比10大的数组则使用 `QuickSort`-快速排序
> > 
> > 详情见[V8 引擎array源码](https://github.com/v8/v8/blob/ad82a40509c5b5b4680d4299c8f08d6c6d31af3c/src/js/array.js) 710行开始 快排在760行处
> 
> * 【4】说干就干！来手写个快排！参考之前写过的一篇[Java题解](https://blog.csdn.net/qq_45704942/article/details/116448702?spm=1001.2014.3001.5502)（写得贼详细 每一步都拆分开来说了！），这篇文章是参考的leetcode主站的一篇[优秀图解 by 袁厨](https://leetcode-cn.com/problems/sort-an-array/solution/dong-hua-mo-ni-yi-ge-kuai-su-pai-xu-wo-x-7n7g/)~（好家伙连环参考）
> 
> 快排分以下几步
> 
> 1.选出基准值
> 
> 2.使用[填坑法](https://leetcode-cn.com/problems/sort-an-array/solution/dong-hua-mo-ni-yi-ge-kuai-su-pai-xu-wo-x-7n7g/)，写一个partition函数将数组分为小于基准值和大于基准值两部分
> 
> 3.递归完成快排！
> 
> 下面代码里这个注释很清楚了吧！
> 
> 另外还写了个[题解](https://leetcode-cn.com/problems/sort-an-array/solution/javascriptjava-chao-xiang-xi-ti-jie-tian-dsvc/) 搭配图看着更舒服哈~
> 
> ```js
> var sortArray = function(nums) {
>     quicksort(nums, 0, nums.length - 1)// 调用快排方法
>     return nums
> };
> var quicksort = function(nums, low, high) {
>     if(low < high) {
>         let index = partition(nums, low, high)// 得到用来将数组分成两部分（左面全小于index 右面全大于index）的索引
>         quicksort(nums, low, index - 1)// 以第一轮得出的index为基准划分出左半区和右半区 对数组的左半区进行递归 将其全部变为有序
>         quicksort(nums, index + 1, high)// 同理左半区
>     }
> }
> var partition = function(arr, low, high) {
>     let pivot = arr[low]// 选定第一个元素为基准值 把它拿出来 即为“挖坑”
>     while(low < high) {
>         // 【1】 挖了坑就需要填坑~从high指针开始向左找 
>         while(low < high && arr[high] >= pivot) {
>             high--
>         }
>         arr[low] = arr[high]// 一旦找到比坑对应值pivot小的 就扔到low那侧的坑里
>         // 【2】 同【1】从low指针开始向右找填坑值
>         while(low < high && arr[low] < pivot) {
>             low++
>         }
>         arr[high] = arr[low]// 一旦找到比坑对应值pivot大的 就扔到high那侧的坑里
>         //（刚刚这侧有一个值去填low那侧的坑了 所以出现了一个坑位~）
>     }
>     // 经过上面【1】【2】的不断迭代 low===high 此时这个位置即为基准位置
>     arr[low] = pivot
>     return low// 分区成功！返回定海神针~（此时low=high哦~）
> }
> ```
> 
> > 再拓展补充下~
> > 
> > * 不稳定的四种排序方法 **快选希堆**
> > * 最快的排序方法是**归并排序** 还有一个不常见的堆排序！ 时间复杂度为 n×log~n~
> >   
> >   * 快速排序的平均时间复杂度是n×log~n~
> >   
> >   ![img](https://camo.githubusercontent.com/59cd33224ae938bb02f6aa07248259d1bbd4c8365f2c5832f6aa7cc4956f6040/68747470733a2f2f70332d6a75656a696e2e62797465696d672e636f6d2f746f732d636e2d692d6b3375316662706663702f37663739613736666135323234343039626463656138656435636566313437307e74706c762d6b3375316662706663702d7a6f6f6d2d312e61776562703f)
> > * 归并排序和快速排序的区别：
> >   ![img](https://camo.githubusercontent.com/18a59ce403bd6d008e0df1fa926df6e7f622954b866092037d0c7ec86623dc2e/68747470733a2f2f70362d6a75656a696e2e62797465696d672e636f6d2f746f732d636e2d692d6b3375316662706663702f34333161633138376437616334333331616263333730323430376333616231367e74706c762d6b3375316662706663702d7a6f6f6d2d312e61776562703f)
> >   
> >   * 归并是先拆开 从底下往上面排
> >   * 快排是每次都打乱一下 从上往下排

本质上感觉就是 利用各种API逐一比较、哈希表、排序后冒泡比较 这几种 还有么 想不出来了 集思广益一波
